android_binary(
    name = "SmartReplyDemo",
    srcs = glob([
        "java/**/*.kt",
        "java/**/*.java",
    ]),
    aapt_version = "aapt",
    assets = [":assets"],
    assets_dir = "",
    custom_package = "lt.setkus.smartreply",
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
)
